name: NPM publish CD workflow

on:
  release:
    types: [published]

jobs:
  NPM-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/cache@v3
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Set publisher name
        run: git config --global user.name "GitHub publish bot"

      - name: Set publisher email
        run: git config --global user.email "github-publish-bot@email.com"

      - name: Bump the application version (package.json)
        run: npm version ${{ github.event.release.tag_name }}

      - name: Build application
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Push version update (package.json)
        uses: peter-evans/create-pull-request@v4
        with:
          title: Updating package.json version to ${{ github.event.release.tag_name }}
          commit-message: 'release: version update'


